apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  namespace: guestbook
  annotations:
        
spec:
  rules:
  - host: guestapp.myapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-ui
          servicePort: http
