apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui

spec:
  rules:
  - host: 
    http:
      paths:
      - path: /guestbook-ui
        backend:
          serviceName: guestbook-ui
          servicePort: http
